//#ifndef GMOpenMix_h
//#define GMOpenMix_h
////confuse string at 2018年 4月11日 星期三 14时28分24秒 CST
//#define pressAction MQHwaLjaMDGFfmQl
//#define canPerformAction VBEKLkWdybUaeeQK
//#define withSender yVaynJGfzfnRSBte
//#define customCopy ChrjpZwmlPLxSvaJ
//#define longPressAction fGZYFWqvUoihoguq
//#define strokeEndAnimation SqcnuRDwqkhSXIRK
//#define strokeStartAnimation zEYzmzeFJPDpVgIn
//#define animationGroup HNdLCkLYlRGpxkJN
//#define rotateZAnimation LUWrgnAbjIYnmyhh
//#define beginAnimation eoRgstmPwJrasenr
//#define beginGradulaAnimation iNNOHSFmxZkxKLlB
//#define beginNormalAnimation HHmBYPfRhFuQDhTQ
//#define endAnimationWithCompletion eLdzwmlZyGakvnrZ
//#define showMessage OwqynDRlFaSSpopG
//#define removeMSGView XwaAKuGUNkdYuRNd
//#define Text wwZjCSYsXjJYctaG
//#define setRedDot pJrzpcnJllXDgGLx
//#define hideKeyboard OxlakyVhDEpdWoht
//#define showView fcSHiUdiTFgguWSf
//#define configView EXiiRkwuMDlpBpkl
//#define backBtnClick FaeYOJcuwUhYNkBD
//#define clostBtnClick DRTytFBmWbGLjluL
//#define dismiss wuSwEQBYKQHvACWL
//#define ServiceShow wuHcMPiQSCsbfloy
//#define saveImage rlnysPJSfqQvxqpH
//#define setLabtitle MbgqSMSNeEawlMYH
//#define qqService JWoslNIUPqtTQbTF
//#define joinGroup aTVOMHwLYxfAsMbk
//#define removeView FpgtFoUaYVJnvKib
//#define setBtnTitle OvmCRLxwcnTjRImw
//#define pullMethod RfNdnmBdqKJcMHEY
//#define checkMethod sILkzjAhiOfQNtTZ
//#define titleMethod sSOIFKnuXiOVQZoo
//#define forgetMethod VbfloaKeRtyATjmW
//#define codeMethod OWspcubJmLInJLsV
//#define promptView ueaPJOyyOuuGqwwI
//#define showLoadView eRzZHWmAlTGDfSvT
//#define hideLoadView ztsEgSJSlGMaxsqQ
//#define agreementView yINXBxOTBQXFgopq
//#define imageFromViewAccount KTBwLzumZJWwjUIt
//#define removeAgreementView NYcGcwbQgTqTfGoD
//#define saveImageToPhotos bcmOMEPSiZmZKJMp
//#define removeImgView obIFoZjVYCtQbABT
//#define select vTASOQQUXprhrzLP
//#define initView JnoVdGTfFewDrnVl
//#define buy vNezEapbNapgGBWM
//#define requestProductData YQvocanEwnjPcOax
//#define postReceipt yqOzUomUuxtqSBtF
//#define Back oIdbQwjiFfwWZlbh
//#define makeUserCallBack PGStaeklFBeTYRBb
//#define AppStore BubjziwLKmdupkkl
//#define OtherPay oXsMOjPtjgrQoKtt
//#define isMoney BHFdmRisQaiPqNVI
//#define Encode gJMmHxWnrXFWilPe
//#define resizeWindow aeOCTHbwQOSvagfx
//#define reachabilityChanged lLySGrzotdPVPwzw
//#define updateInterfaceWithReachability UUgEqMUPxsAYMpey
//#define setDelIcon AmvjIbRfKZKkPrcS
//#define showbar ShetuHXSbYLZreqT
//#define hidenbar rWzhYJvmDBNlXoeV
//#define TouchUp hGWnpyKfbejFSkVF
//#define chargeViewLocation AERAPIyEeMLskgZg
//#define configEntryView wiAJTZtQxXdjsDkN
//#define handlePan XCBGDQoDXDFqyUAL
//#define TouchDown mnuyahrMKWaWLoxM
//#define isDelToolBar RTIOhTZGvuivPPMI
//#define initData iJgQiJGkZmrcZfkS
//#define promoteCoin tibrEcIqymwVafrG
//#define addBeardFromPoint FfFOcdJvCBYfDXCN
//#define toPoint MMEBhjNDYtTqHdgI
//#define setData juMAVKFydNUJVKYF
//#define initList MTqgtJTBJoLtYHAq
//#define questionTouch TSKsqaucOdgDwVzF
//#define addLine JszaxNtxrIKFdvtR
//#define redDotAddMy ZErdhWhwKtwVHHFN
//#define redDotDelMy SRkRTPtMgXGsojGO
//#define redDotAddInfor qasyhyPuwxugoqrr
//#define redDotDelInfor ePBURCQFXMeHWjvZ
//#define Checked JiAIGlefaQycstoI
//#define closeGMGiftBagTableViewCell zdBoqghwDYAeOzji
//#define addSelected aHgmRVLDxKUKAWgy
//#define unfoldAndclose LHoRHGxmRrXxsZDf
//#define btnTouch mhnxgpkzfNePFKHC
//#define setBtnIsClick AHGYNyemmaPcurvH
//#define closeTouch tdNWajnojyZnqBdO
//#define retreatTouchUp gsthWiOZBjCRNXbf
//#define goforwardTouchUp LhijNnnQdXtorasW
//#define updateTouchUp gfpQDdZQtXpJcYUP
//#define homeTouchUp zpQaxBFBMHqLVwAv
//#define initdata GUDCcjrdlhEYFCZj
//#define GMManeuverTableViewBack HPlcSvDKOfKSnjMX
//#define addWebView DIlxkzHRkEFaxgCq
//#define closeWebView nRyNdFkKthIcxrwh
//#define close SoHRMcgSiiENZXnu
//#define bottomView JiKkVgCSIGwQQbYm
//#define switchlogin BLSvyvLmKgcNZetX
//#define binding LMLdtonbxNkLslwL
//#define giftbag HYeFHotrXHZCZCWU
//#define maneuverTouchUp QUwYPIvLYjtDwczf
//#define accountTouchUp OgQyqZSyRVjhiXSD
//#define airline XPUskFDjLaRKWfom
//#define analysisPutInData KuMTKAEDhDNfXWSU
//#define refreshInfo lpifWLmUGaFEDXZh
//#define account qdQAyjwqjPQndQlM
//#define GMUserinfoFromServiceBack eTniiutuasEmKUDy
//#define getSwitch JzOPeIXmVPjHENEk
//#define getUserinfoFromService CokmCtyKiUUSNiHR
//#define backmodel MKntPSPzfNWtCxGO
//#define agreement mRZriTPfSvvHzdVg
//#define pwdel ixeNYvwAgyWMwayR
//#define fastLoginClick KvdwOnhdeIvrIAhS
//#define tokenLogin gWlsRkRXcqGYTmYn
//#define passWordLogin qJijYkarHgBUnLVq
//#define fastLogin csbmYUSAnkexSyzU
//#define registerBtn tDuXlZKGVvIvrZRE
//#define forgetPW XAvmQTEtjLsnRcIp
//#define codeLoginTouch tEOUebNbCtpKaUPh
//#define codeView HpKFHDXSxdyYRETW
//#define passwordView gHAsGRgVkAXzGJvZ
//#define dropHide jQhgCNBnNqcefeLY
//#define GMDropDownRefreshMethod FcSMgHiLFjxAjdvI
//#define GMDropDownDelegateMethod fdrHCgObxYQOOsYd
//#define hideDropDown kLEyKByPPlqrMoTR
//#define aotoAddAccount zlcFZNUHXxGZehpW
//#define GetVerifiCodeButtonClick grdukoirwMIHrvjN
//#define QQLogin TUVTpnIdQCVBYlbL
//#define WBLogin YXpXoDPBioonsOOf
//#define hide biLfHOYEKrJaUFCI
//#define getLastUid LAfWkbFHzdACBtXm
//#define addCount mFVzDiuxaCfVmqym
//#define nextBtnClick HzLbRTDSOFHwFhGL
//#define fastLoginuid lNYKDRESuEHbTjBs
//#define imageRatationImageView monuJPujkGUWbbQv
//#define loginSuccess SRcxZCdWnqHwqykQ
//#define changeAccountBtnClick HtmofPpIjUcrPQUb
//#define configClose oTkCcPtlwsBraDOU
//#define closePage bBOpYocWhAaNjmaE
//#define configUI omRsEHvfkQsoKGQe
//#define urlFormat CXPjbUVreQxrTSgY
//#define LoginSuccess lunExNofyimYSQae
//#define forgetpassword FTtdGjRJmVDUAwpS
//#define reg VlROnXonxnxaxMME
//#define banding tGoOOWSwFcdIKEFD
//#define closePlatform fCgvKziZwJXJoBkP
//#define doSelectLoginType xxAIPQTGVxxQqYXa
//#define checkoutLastUid sPEUnvopVNwzrEMm
//#define handleLoginResult lVdpxkpEUbNDigRY
//#define switchlogout zltZHLrIUfgyPZWJ
//#define getUserInfo rpcnjkMOZMKyYcYK
//#define doRegAndForget BOuVcGnuwBlRRICm
//#define doswichaccount myjAsXtxWtHzpTKT
//#define doLoginPhone_list LzUiCiZbjnrnhHQP
//#define doLoginPhone HqQrODRZXBkxGUJD
//#define loginSuccessDialog vcoHqMFpRDiPcZcC
//#define UserInfoToNSDictionary kvjJZfsNHjOCCpTg
//#define NSDictionaryToUserInfo ilOfSeWNTXRAhqXU
//#define deleteAccount DMCedqLugHMHSklP
//#define myDelegate ciBlkPVuZdWYhHYB
//#define saveCurrentUserInfo bbWZOOnKOFeyFVbL
//#define getUserLoginInfoList DHBfqLlmFBAykBbi
//#define delUserInfoToken pllVLpDlHHbufXFN
//#define userNameDeleteToPlist KsWlidjRyIgaOmDD
//#define setFastLogin anbEnboWNDEBkxjt
//#define getFastLogin UTZfIXTbGuNPYZAr
//#define getAuthCode TPmnoLfelNfIzsfi
//#define getUpTime hJWNusNRribvOpbC
//#define timeFireMethod USKBhRTWCNjoRGhg
//#define getDeviceId FgilHKYsiTsvVFbF
//#define getSDCardPath KZQlVgrXuvLYlDwF
//#define getRandomStr ZGvFXjQDCVOswPwn
//#define getOrientation QosFiRAEuJQjJNpF
//#define isPhone REAqyTcrVMtzhoNN
//#define isEmail zmftCuJFTRcZiLit
//#define getVersionCode sEdpVqWyeyDIRHhV
//#define getApplicationName bSSYIraVQxBgGRYA
//#define getBundleID MNJNCWjwXXFCXibB
//#define phoneVersion ITKslYlNKwnooAKB
//#define isStrEmpty afYgcZJFRRtpTWKy
//#define getNowTimes MsHliEOsjiPrNREW
//#define transformSighKey qBQBSBnimLdUWhNi
//#define dictionaryWithJsonString CfTuSAdkrlMTOgXO
//#define dictionaryToString fQmIuRqKgGSnlaRl
//#define checkForNumberAndCase hTBFEcPlBpbHPNPV
//#define checkForLowerCase rvMzmjHYrNyViBvX
//#define checkForUpperCase iskfTuWDNcGSCCgo
//#define checkForLowerAndUpperCase ePzNGSUVpXBpxNoT
//#define checkForSpecialChar IzWhZWYpGPRRCJya
//#define checkForNumber PTxWYVCuylAymLUI
//#define checkForNumberWithLength dLutNxmTQWYgUsUJ
//#define checkForUsername JWlMWDTVCOLKFzDU
//#define checkForBlank fYmJBHtaQAFkfImh
//#define getImageFromBundle dYrgCuVwSlMKOUzy
//#define removeAllViewChildren PLbbzQVmLUIJclpM
//#define viewFit aWQweKlkOdNZIdzx
//#define viewFitCancel BNjQuIoISDJiobqp
//#define getNetWorkStates bPEJcuHqDhVoeclL
//#define getString RmzQtliDknklVDeS
//#define isNetWork SVbaSmXhmYsnMfDu
//#define DictionaryTOUrlString qCCJlEXLzicARPOF
//#define getColor elYOPHMmFMeXyXHQ
//#define onEvent EeYShKfoShfWjymY
//#define setName urrqUIuoxryjXibl
//#define addUserNewbieguide fJAqlDVjkutEquFA
//#define heartBeatUpLoadInfo estgsynyzQBDkuZX
//#define heartBeatRequest UjfcmNvFZjBrbhMX
//#define TS EJzKLTxgeEqxYbUE
//#define GMPayCentral ygLXeIRFToBTbEPf
//#define GMAppleIAP lKZBwoiRXZrzClmd
//#define GMToolbarView nQIhjzBpuivMvXrJ
//#define GMCloseToolBar tgACAaNdLHvVzQYb
//#define GMCoupon PVJYhJlWuGAomNma
//#define GMGiftBag DNCgtmiTpSjPHQHK
//#define GMCouponTableView ueyCrMKlSyHKoYRb
//#define GMCouponTableViewCell vZOyqrMQdXSisvYD
//#define GMGiftBagTableView DwFhlfoJqRxyeKfc
//#define GMGiftBagTableViewCell mKRjhzBwjeNdiYOk
//#define GMLookGiftBag JWNmyjBjjNtNQuae
//#define GMManeuver UQeBQLIUnIWiXEsI
//#define GMMyCenter dgjKWSlobHSFmyYZ
//#define GMPersonalCenter wPZoVVMPvtdLBCdZ
//#define GMManeuverWebView GAqYLpYaRALzFgVT
//#define GMNewMessageHint bzbXflFefWFApLju
//#define GMUserinfoFromService UjHdinZIAHFXMdLc
//#define GMLoginByPhoneDialog wwgrBvIckluHPbyV
//#define GMLoginSuccess gBWmOYPLewePWTzM
//#define GMOtherLoginWebView eGYXxvbBKdDTERpT
//#define GMRegisterAndForgetPassWord vrMTbdLkcgBQcRXz
//#define GMSDKCallBack vfkRRXPSFCfqDjtW
//#define GMUserCentral spZXXagJCiJWtepX
//#define GMCopyLable NhxqdMbUwiOmOoKR
//#define GMProgressHelper vMzKczjXrAUEgrHv
//#define GMTextField vikiPSNwJgrZKLpN
//#define GMToast oowvOGxxaKgYZDCH
//#define GMButton pJhjJbFDURpuaUDy
//#define GMController QdPVpUVaUAndeVvN
//#define GMRedDot SDsCHlrrIQGnZiLR
//#define GMSDKCentral NXxtXaKLQNCGfntt
//#define GMSDKConfig cEpoXgsyGNxnqskX
//#define GMDropDown qSujAuOZyOYEFwQJ
//#define GMSaveLoginData cGZASDBWsGtTPdfH
//#define GMAuthCode booofBNtwqxEvYjN
//#define GMDeviceInfo qBjStuKobOiCIprT
//#define GMReachability WnaEiFPnsaFfoVcm
//#define GMHttpInvoker bwNlLquCzggVJkCi
//#define GMUCommUtil lWasznokIfSPwLqb
//#define GMUserInfo wtCOgFVulyyJElAp
//#define PAY_SUCCESS MArxPDPmaXKHGPll
//#define PAY_FAILED lQQvhRIhOVxpNUNk
//#define PAY_CANCEL JZmEpjypeEQmdLWs
//#define PAY_UNKNOWN pxgQuaUQnskuzWuA
//#define GMCustomerServices LMhuJiSCZbkCXUaC
//#define GMTextFieldView KYNSULLRwgqOFxmw
//#define GMTracestatistic ZPxhNzRocKcInpWY
//#define GMCountryListView qxWjMxNZCIHQLyOG
//#define GMPromptView nGQYQLytmHZPHBWz
//#define GMLoginDefaultMode fbHlWhznYGZGgImK
//#define GMAccountDetails OVzrQaCpIrAgeirn
//#define GMAirline niFUEMpvwhqZyReq
//#define GMDoubleButton pvmNAUBUrUmzTims
//#define GMInformationListView ufSAuPzURtUALMla
//#define GMInformationTableView sxGebuogBbZjZhLQ
//#define GMManeuverTableView qoOzylYxaMqvBtBo
//#define GMManeuverTableViewCell dtSLotpvdfaDfXPf
//#define GMUStatisticsUtil jglRjzcpxbBfYbVw
//#endif

